#!/bin/sh

# check for xtrace flag
while getopts :hx opt; do
	case "$opt" in
	x)
		set -o xtrace
		;;
	h)
		printf 'usage: %s [-x] <lind program path>\n' "${0##*/}" >&2
		exit
		;;
	:|?)
		printf 'illegal option letter: %s\n' "'$OPTARG'" >&2
		printf 'usage: %s [-x] <lind program path>\n' "${0##*/}" >&2
		exit 1
		;;
	esac
done
shift "$((OPTIND - 1))"

export LIND_PREFIX="${LIND_PREFIX:-$HOME}"
export LIND_BASE="${LIND_BASE:-$LIND_PREFIX/lind_project}"
export LIND_SRC="${LIND_SRC:-$LIND_BASE/lind}"
export LIND_MONITOR="${LIND_MONITOR:-$LIND_BASE/reference_monitor}"
export REPY_PATH="${REPY_PATH:-$LIND_SRC/repy}"
export NACL_SDK_ROOT="${NACL_SDK_ROOT:-$REPY_PATH/sdk}"
export PYTHON="${PYTHON:-python2}"
export PNACLPYTHON="${PNACLPYTHON:-python2}"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-/lib/glibc}"

cwd="$PWD"
trap 'cd "$cwd"' EXIT

cd "$REPY_PATH/repy" || exit 1

sel_ldr -a -- "$LD_LIBRARY_PATH/runnable-ld.so" --library-path "$LD_LIBRARY_PATH" "$@"
